songs/Tyle_mi_zostalo_co_mi_nakapalo.xml

- poprawki głównie danych twórcy
- oznaczenie refrenu jako refren.

Piosenka: Tyle mi zostało co mi nakapało

---

songs/Miejcie_nadzieje.xml

Zmiana twórców
[Link do edytora](https://ptabor.github.io/songbook/editor?&baseUrl=http%3A%2F%2Flocalhost%3A8080&branch=se-2022-10-26-5568-Miejcie_nadzieje.xml&file=songs%2FMiejcie_nadzieje.xml&user=ptabor)

Piosenka: songs/Miejcie_nadzieje.xml

---

.gitignore
editor-github/.gcloudignore
editor-github/.gitignore
editor-github/common.js
editor-github/deploy.sh
editor-github/editor-github.iml
editor-github/exp.js
editor-github/google-cloud-functions-env.txt
editor-github/index.js
editor-github/listChanges.js
editor-github/local-env.txt
editor-github/package-lock.json
editor-github/package.json
editor-github/template-env.txt

Pozwala poprawiać XMLe bez konieczności instalacji git'a na lokalnej maszynie.

Integracja edytora piosenek z githubem

---

songs/Bagno.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?&baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-10-27-5257-Bagno.xml&file=songs%2FBagno.xml&user=ptabor)

Piosenka: songs/Bagno.xml

---

editor/sanitize.js
editor/song.css
editor/songbody.js

It was not possible if the last verse was the 'referenced' chorus.

Editor: Button to add verse

---

.github/workflows/generate.yml
render_epub.sh
render_htmls.sh
songs/10_w_skali_Beauforta.xml
src/epub/create_epub.py
src/html/create_songs_html.py

fixes https://github.com/wdw21/songbook/issues/26

Branch with changes html-> xhtml and epub and zip generation

---

songs/Kolysanka_dla_misiakow.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-11-29-3515-Kolysanka_dla_misiakow.xml&file=songs%2FKolysanka_dla_misiakow.xml&user=Adam-Foland)

Piosenka: songs/Kolysanka_dla_misiakow.xml

---

songs/Raport_z_izby_otrzezwien.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-11-19-4807-Raport_z_izby_otrzezwien.xml&file=songs%2FRaport_z_izby_otrzezwien.xml&user=ptabor)

Piosenka: songs/Raport_z_izby_otrzezwien.xml (Wódka, tylko wódka)

---

songs/Kaszubskie_noce.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-12-31-4850-Kaszubskie_noce.xml&file=songs%2FKaszubskie_noce.xml&user=ptabor)

Piosenka: songs/Kaszubskie_noce.xml

---

songs/Always_look_on_the_bright_side_of_life.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-01-9102-Always_look_on_the_bright_side_of_life.xml&file=songs%2FAlways_look_on_the_bright_side_of_life.xml&user=wdw21-druh)

Piosenka: songs/Always_look_on_the_bright_side_of_life.xml

---

songs/Gdansk.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-12-29-405-Gdansk.xml&file=songs%2FGdansk.xml&user=ptabor)

Piosenka: songs/Gdansk.xml

---

songs/Tyle_mi_zostalo_co_mi_nakapalo.xml

[Link do edytora](https://ptabor.github.io/songbook/editor?baseUrl=https%3A%2F%2Fsongbook-gh6-j72bw4qyaq-ew.a.run.app&branch=se-2022-12-28-2949-Tyle_mi_zostalo_co_mi_nakapalo.xml&file=songs%2FTyle_mi_zostalo_co_mi_nakapalo.xml&user=ptabor)

Piosenka: songs/Tyle_mi_zostalo_co_mi_nakapalo.xml

---

songs/Piesn_pozegnalna.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-02-8621-Piesn_pozegnalna.xml&file=songs%2FPiesn_pozegnalna.xml&user=ptabor)
[object Promise]

Piosenka: songs/Piesn_pozegnalna.xml

---

songs/Nocny_kawboy.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-02-3428-Nocny_kawboy.xml&file=songs%2FNocny_kawboy.xml&user=ktab15)
Piosenka Nocny kawboy: Initial
Piosenka Nocny kamboj: poprawka wg kaczmarski.art.pl
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-02-3428-Nocny_kawboy.xml&file=songs%2FNocny_kawboy.xml&user=ktab15) by nanieść dodatkowe poprawki.

Piosenka: songs/Nocny_kawboy.xml

---

songs/Kocham_Cie_jak_Irlandie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-02-4584-Kocham_Cie_jak_Irlandie.xml&file=songs%2FKocham_Cie_jak_Irlandie.xml&user=ptabor)
Piosenka Kocham Cię jak Irlandię: Initial
Piosenka Kocham Cię jak Irlandię: Wyróżniłem akordy i dodałem autora tekstu
Piosenka Kocham Cię jak Irlandię: Poprawki ostatniego refrenu

Piosenka: songs/Kocham_Cie_jak_Irlandie.xml

---

songs/Let_it_be.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-04-8673-Let_it_be.xml&file=songs%2FLet_it_be.xml&user=ptabor)
Piosenka Let it be: Initial
Piosenka Let it be: To był jakiś bałagan totalny
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-04-8673-Let_it_be.xml&file=songs%2FLet_it_be.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Let_it_be.xml

---

songs/Panna_kminkowa.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2022-11-14-9581-Panna_kminkowa__2_.xml&file=songs%2FPanna_kminkowa.xml&user=Adam-Foland)
Piosenka Panna kminkowa: Initial
Piosenka Panna kminkowa: Poprawine częściowo akorty i tekst, zapisujęanim mi wybuchnie jak bde chciał dodać nowe akordy
Piosenka Panna kminkowa: Nie wiem co tu wpisywać
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2022-11-14-9581-Panna_kminkowa__2_.xml&file=songs%2FPanna_kminkowa.xml&user=Adam-Foland) by nanieść dodatkowe …

Piosenka: songs/Panna_kminkowa_(2).xml

---

songs/Zbroja.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-08-9766-Zbroja.xml&file=songs%2FZbroja.xml&user=Adam-Foland)
Piosenka Zbroja: Initial
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-08-9766-Zbroja.xml&file=songs%2FZbroja.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Zbroja.xml

---

editor/save.xslt
editor/sidechords.js
editor/testsong.xml
editor/verse.js
src/latex/song2tex.py

1. Better export of instr rows to xml.
2. XML->Tex knows how to handle instr='never'
3. Navigation in side-chords.

Improving to instrumental rows and side-chords

---

songs/Ambasadorowie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-24-6059-Ambasadorowie.xml&file=songs%2FAmbasadorowie.xml&user=ptabor)
Piosenka Ambasadorowie: Initial
Piosenka Ambasadorowie: Akordy nad tekstem jeszcze nie ustawione
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-24-6059-Ambasadorowie.xml&file=songs%2FAmbasadorowie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Ambasadorowie.xml

---

songs/A_Wee_drap_O_Whisky.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-27-7997-A_Wee_drap_O_Whisky.xml&file=songs%2FA_Wee_drap_O_Whisky.xml&user=ptabor)
Piosenka A  Wee drap O' Whisky: Initial
Piosenka A  Wee drap O' Whisky: Fix chord types
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-27-7997-A_Wee_drap_O_Whisky.xml&file=songs%2FA_Wee_drap_O_Whisky.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/A_Wee_drap_O_Whisky.xml

---

songs/A_my_nie_chcemy_uciekac_stad.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-22-3434-A_my_nie_chcemy_uciekac_stad.xml&file=songs%2FA_my_nie_chcemy_uciekac_stad.xml&user=ptabor)
Piosenka A my nie chcemy uciekać stąd: Initial
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-22-3434-A_my_nie_chcemy_uciekac_stad.xml&file=songs%2FA_my_nie_chcemy_uciekac_stad.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/A_my_nie_chcemy_uciekac_stad.xml

---

songs/Panna_kminkowa.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-1245-Panna_kminkowa.xml&file=songs%2FPanna_kminkowa.xml&user=Adam-Foland)
Piosenka Panna kminkowa: Initial
Piosenka Panna kminkowa: potem
Piosenka Panna kminkowa: akordy
Piosenka Panna kminkowa: Czemu mam zapisywać zaminy jak sobie zapisuje kopie w trakcie robienia?
Piosenka Panna kminkowa: Akory, akordy nad tekstem, twórcy i wykonawcy, drobny błąd w tekście
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-1245-Panna_kminkowa.xml&fi …

Piosenka: songs/Panna_kminkowa.xml

---

songs/Wspomnienia.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-8183-Wspomnienia.xml&file=songs%2FWspomnienia.xml&user=ktab15)
Piosenka Wspomnienia: Initial
Piosenka Wspomnienia: Tekst sprawdzony
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-8183-Wspomnienia.xml&file=songs%2FWspomnienia.xml&user=ktab15) by nanieść dodatkowe poprawki.

Piosenka: songs/Wspomnienia.xml

---

songs/Pan_Kmicic.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-2676-Pan_Kmicic.xml&file=songs%2FPan_Kmicic.xml&user=Adam-Foland)
Piosenka Pan Kmicic: Initial
Piosenka Pan Kmicic: tmp
Piosenka Pan Kmicic: tmp2
Piosenka Pan Kmicic: Akordy+ nad tekstem, intro, tekst, album
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-29-2676-Pan_Kmicic.xml&file=songs%2FPan_Kmicic.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Pan_Kmicic.xml

---

songs/Opadly_mgly_wstaje_nowy_dzien.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-19-Opadly_mgly_wstaje_nowy_dzien.xml&file=songs%2FOpadly_mgly_wstaje_nowy_dzien.xml&user=ptabor)
Piosenka Opadły mgły wstaje nowy dzień: Initial
Piosenka Opadły mgły wstaje nowy dzień: Poprawiono akordy nad referenem
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-19-Opadly_mgly_wstaje_nowy_dzien.xml&file=songs%2FOpadly_mgly_wstaje_nowy_dzien.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Opadly_mgly_wstaje_nowy_dzien.xml

---

songs/Pozegnanie_2.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-31-3456-Pozegnanie_2.xml&file=songs%2FPozegnanie_2.xml&user=Adam-Foland)
Piosenka Pożegnanie 2: Initial
Piosenka Pożegnanie (SDM): Sprawdzenie i drobne korekty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-31-3456-Pozegnanie_2.xml&file=songs%2FPozegnanie_2.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Pozegnanie_2.xml

---

songs/Koncert.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-31-6628-Koncert.xml&file=songs%2FKoncert.xml&user=Adam-Foland)
Piosenka Koncert: Initial
Piosenka Koncert: Twórcy, wykonawcy, prprawki bisów w refrenach + drobiazgi
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-31-6628-Koncert.xml&file=songs%2FKoncert.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Koncert.xml

---

songs/Gloria.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-9511-Gloria.xml&file=songs%2FGloria.xml&user=Adam-Foland)
Piosenka Gloria: Initial
Piosenka Gloria: tekst i twórcy
Piosenka Gloria: akordy z boku
Piosenka Gloria: ostatnie porwki
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-9511-Gloria.xml&file=songs%2FGloria.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Gloria.xml

---

songs/czas.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-7775-czas.xml&file=songs%2Fczas.xml&user=ptabor)
Piosenka Czas: Initial
Piosenka Czas: Poprawka ważności akordów.
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-7775-czas.xml&file=songs%2Fczas.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/czas.xml

---

songs/Piesn_na_wejscie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-7099-Piesn_na_wejscie.xml&file=songs%2FPiesn_na_wejscie.xml&user=ptabor)
Piosenka Pieśń na wejście: Initial
Piosenka Pieśń na wejście: Typy akordów
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-30-7099-Piesn_na_wejscie.xml&file=songs%2FPiesn_na_wejscie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Piesn_na_wejscie.xml

---

songs/Ballada_o_Dzikim_Zachodzie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-02-06-1615-Ballada_o_Dzikim_Zachodzie.xml&file=songs%2FBallada_o_Dzikim_Zachodzie.xml&user=ptabor)
Piosenka Ballada o Dzikim Zachodzie: Initial
Piosenka Ballada o Dzikim Zachodzie: Oznaczy¬em refreny
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-02-06-1615-Ballada_o_Dzikim_Zachodzie.xml&file=songs%2FBallada_o_Dzikim_Zachodzie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Ballada_o_Dzikim_Zachodzie.xml

---

songs/Dom_w_gorach.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-02-12-2781-Dom_w_gorach.xml&file=songs%2FDom_w_gorach.xml&user=Adam-Foland)
Piosenka Dom w górach: Initial
Piosenka Dom w górach: Tekst, ostatni refren, autorka, uwagi
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-02-12-2781-Dom_w_gorach.xml&file=songs%2FDom_w_gorach.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Dom_w_gorach.xml

---

songs/Dzielna_Margot.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-02-20-2280-Dzielna_Margot.xml&file=songs%2FDzielna_Margot.xml&user=ptabor)
Piosenka Dzielna Margot: Initial
Piosenka Dzielna Margot: Akordy nico rozmieszczono
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-02-20-2280-Dzielna_Margot.xml&file=songs%2FDzielna_Margot.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Dzielna_Margot.xml

---

songs/Ballada_rajdowa.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-02-20-3354-Ballada_rajdowa.xml&file=songs%2FBallada_rajdowa.xml&user=ptabor)
Piosenka Ballada rajdowa: Initial
Piosenka Ballada rajdowa: Literówki
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-02-20-3354-Ballada_rajdowa.xml&file=songs%2FBallada_rajdowa.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Ballada_rajdowa.xml

---

songs/Polow.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-03-06-9143-Polow.xml&file=songs%2FPolow.xml&user=Adam-Foland)
Piosenka Połów: Initial
Piosenka Połów: Brakująca linijka, błędy w tekście, porządek w akordach
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-03-06-9143-Polow.xml&file=songs%2FPolow.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

Piosenka: songs/Polow.xml

---

songs/cos.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-12-29-9099-cos.xml&file=songs%2Fcos.xml&user=sfc-gh-ptabor)
Piosenka Coś: Initial
Piosenka Coś: Testowy edit
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-12-29-9099-cos.xml&file=songs%2Fcos.xml&user=sfc-gh-ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/cos.xml

---

songs/Krakow_Piwna_7.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-06-23-6481-Krakow_Piwna_7.xml&file=songs%2FKrakow_Piwna_7.xml&user=ptabor)
Piosenka Kraków, Piwna 7: Initial
Piosenka Kraków, Piwna 7: Dodałem zespół i oznaczyłem autora tekstu
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-06-23-6481-Krakow_Piwna_7.xml&file=songs%2FKrakow_Piwna_7.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Krakow_Piwna_7.xml

---

songs/Czarny chleb i czarna kawa.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-12-30-443-Czarny_chleb_i_czarna_kawa.xml&file=songs%2FCzarny+chleb+i+czarna+kawa.xml&user=ptabor)
Piosenka Czarny chleb czarna kawa: Pierwsza wersja piosenki
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2023-12-30-443-Czarny_chleb_i_czarna_kawa.xml&file=songs%2FCzarny+chleb+i+czarna+kawa.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Czarny chleb i czarna kawa.xml

---

src/epub/create_epub.py
src/epub/templates/content.opf
src/epub/templates/index.xhtml
src/epub/templates/song.css
src/epub/templates/template.css
src/epub/templates/toc.ncx
src/epub/templates/toc.xhtml
src/epub/templates/toc_letter.xhtml
src/html/create_songs_html.py

Indexing fixes.
- disabled ncx - as deprecated
- added index file
- added doctype headers to xhtml
- added list of letters to each index page.

EPub: Index/Toc fixes

---

songs/pila_tango.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-12-1615-pila_tango.xml&file=songs%2Fpila_tango.xml&user=ptabor)
Piosenka Piła tango: Pierwsza wersja Piły Tango
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-12-1615-pila_tango.xml&file=songs%2Fpila_tango.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pila_tango.xml

---

songs/Zycie_to_nie_teatr.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-12-3099-Zycie_to_nie_teatr.xml&file=songs%2FZycie_to_nie_teatr.xml&user=ptabor)
Piosenka Życie to nie teatr: Initial
Piosenka Życie to nie teatr: Dodałem brakujący refren
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-12-3099-Zycie_to_nie_teatr.xml&file=songs%2FZycie_to_nie_teatr.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/Zycie_to_nie_teatr.xml

---

containers/Dockerfile
containers/apko/latex.apko.yaml
render_epub.sh
songbooks/default.songbook.yaml
songbooks/smoke.songbook.yaml
src/epub/create_epub.py
src/html/create_songs_html.py
src/html/htmls_generator.py

- **List of songs [to render] can be driven by foo.songbook.yaml file.**
- **Intall py-yaml in the docker images.**
- **Fixed spaces between lines in epub. Added songbook spec.**

Adding specification of songbook as YAML.

---

.github/workflows/publish_page.yml

- **Configure for rendering of the default songbook.**
- **Adding source-change presubmit.**
- **Publish should trigger generate_all after name.**

Publish (post-submit) should trigger renamed generate_all GH workflow.

---

songs/pl/poezja/alpuhara.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-13-7551-pl_poezja_alpuhara.xml&file=songs%2Fpl%2Fpoezja%2Falpuhara.xml&user=ptabor)
Piosenka Alpuhara: Initial
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-13-7551-pl_poezja_alpuhara.xml&file=songs%2Fpl%2Fpoezja%2Falpuhara.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/alpuhara.xml

---

.github/workflows/publish_page.yml

- **EPUBs: Properly templated (and generated) from the songboook spec.**
- **Let's generate index of all songbooks on http page (in index.html).**
- **Add epubcheck.**
- **Fixed.**
- **PDFs are in subdir.**
- **Cleanup.**

20240714 dino songbook

---

.github/workflows/generate_all.yml
.github/workflows/publish_page.yml
src/html/index_generator.py

- **EPUBs: Properly templated (and generated) from the songboook spec.**
- **Let's generate index of all songbooks on http page (in index.html).**
- **Add epubcheck.**
- **Fixed.**
- **PDFs are in subdir.**
- **Cleanup.**
- **Rename.**
- **Improved index.**

Improve (html) index to point on different songbooks in correct location.

---

.github/workflows/publish_page.yml

- **EPUBs: Properly templated (and generated) from the songboook spec.**
- **Let's generate index of all songbooks on http page (in index.html).**
- **Add epubcheck.**
- **Fixed.**
- **PDFs are in subdir.**
- **Cleanup.**
- **Rename.**
- **Improved index.**
- **It's xhtml.**
- **Add index.**

index.xhtml on site (instead of html)

---

.github/workflows/publish_page.yml

- **CSS for index was not linked correctly.**
- **Publishing**

Fix page htmls dir

---

.github/workflows/publish_page.yml
src/epub/templates/song.css
src/html/templates/index.xhtml

- **CSS for index was not linked correctly.**
- **Publishing**
- **Turn off braking the pages.**

Tweak CSS for not forcing verses to be moved as a whole between pages.

---

.github/workflows/generate_changed_pdf.yml

- **CSS for index was not linked correctly.**
- **Publishing**
- **Turn off braking the pages.**
- **Informacja jak wgrać na Kindle'a.**
- **Fix the process for building individual PDFs.**

Fix PDFs as part of precommit 

---

.github/workflows/dispatch_pull.yml
.github/workflows/generate_all.yml
.github/workflows/generate_changed_pdf.yml
containers/build_push_images.sh
containers/login.sh

Hopefully it will speedup local runs (and reduce costs).

Store container in GHCR (github container registry).

---

songs/pl/szanty/Mazurscy_kolumbowie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-23-3405-pl_szanty_Mazurscy_kolumbowie.xml&file=songs%2Fpl%2Fszanty%2FMazurscy_kolumbowie.xml&user=ptabor)
Piosenka Mazurscy kolumbowie: Initial
Piosenka Mazurscy kolumbowie: Fundamentalne problemy
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-23-3405-pl_szanty_Mazurscy_kolumbowie.xml&file=songs%2Fpl%2Fszanty%2FMazurscy_kolumbowie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/szanty/Mazurscy_kolumbowie.xml

---

INSTALL
prepare_context.sh
src/epub/create_epub.py
src/epub/templates/template.css
src/html/create_songs_html.py
src/html/index_generator.py
src/latex/songbook2tex.py
src/lib/list_of_songs.py
test_epub.sh

- **Impreve the installation scripts.**
- **Span the letters apart.**
- **Bring back the songs to generated index.**
- **Aliases present in the epub index.**

Bunch of improvement to the index navigation in epub

---

songs/pl/poezja/leonardo.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-28-69-pl_poezja_leonardo.xml&file=songs%2Fpl%2Fpoezja%2Fleonardo.xml&user=ptabor)
Piosenka Leonardo: Initial
Piosenka Leonardo: Informacja o twórcach
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-07-28-69-pl_poezja_leonardo.xml&file=songs%2Fpl%2Fpoezja%2Fleonardo.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/leonardo.xml

---

songs/pl/poezja/tesknica.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-11-500-pl_poezja_tesknica.xml&file=songs%2Fpl%2Fpoezja%2Ftesknica.xml&user=ptabor)
Piosenka Tęsknica: Initial
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-11-500-pl_poezja_tesknica.xml&file=songs%2Fpl%2Fpoezja%2Ftesknica.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/tesknica.xml

---

songs/pl/folk/kwiat_jabloni/dzis_pozno_pojde_spac.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-6605-pl_folk_kwiat_jabloni_dzis_pozno_pojde_spac.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdzis_pozno_pojde_spac.xml&user=dch-pub)
Piosenka Dziś późno pójdę spać: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-6605-pl_folk_kwiat_jabloni_dzis_pozno_pojde_spac.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdzis_pozno_pojde_spac.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/dzis_pozno_pojde_spac.xml

---

songs/pl/folk/kwiat_jabloni/kto_powie_mi_jak.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-5952-pl_folk_kwiat_jabloni_kto_powie_mi_jak.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fkto_powie_mi_jak.xml&user=dch-pub)
Piosenka Kto powie mi jak: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-5952-pl_folk_kwiat_jabloni_kto_powie_mi_jak.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fkto_powie_mi_jak.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/kto_powie_mi_jak.xml

---

songs/pl/folk/kwiat_jabloni/Lego.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-1150-pl_folk_kwiat_jabloni_Lego.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2FLego.xml&user=dch-pub)
Piosenka Lego: ...
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-12-1150-pl_folk_kwiat_jabloni_Lego.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2FLego.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/Lego.xml

---

songs/pl/poezja/polanska.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-6835-pl_poezja_polanska.xml&file=songs%2Fpl%2Fpoezja%2Fpolanska.xml&user=dch-pub)
Piosenka Polańska: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-6835-pl_poezja_polanska.xml&file=songs%2Fpl%2Fpoezja%2Fpolanska.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/polanska.xml

---

songs/pl/folk/kwiat_jabloni/bylominelo.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-5139-pl_folk_kwiat_jabloni_bylominelo.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbylominelo.xml&user=dch-pub)
Piosenka Byłominęło: ...nowe
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-5139-pl_folk_kwiat_jabloni_bylominelo.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbylominelo.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/bylominelo.xml

---

songs/pl/folk/kwiat_jabloni/moglo_byc_nic.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-4035-pl_folk_kwiat_jabloni_moglo_byc_nic.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fmoglo_byc_nic.xml&user=dch-pub)
Piosenka Mogło być nic: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-4035-pl_folk_kwiat_jabloni_moglo_byc_nic.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fmoglo_byc_nic.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/moglo_byc_nic.xml

---

songs/pl/poezja/juz_lato.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-17-6782-pl_poezja_juz_lato.xml&file=songs%2Fpl%2Fpoezja%2Fjuz_lato.xml&user=dch-pub)
Piosenka Już lato: ...nowa, niestety nie znam autorów
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-17-6782-pl_poezja_juz_lato.xml&file=songs%2Fpl%2Fpoezja%2Fjuz_lato.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/juz_lato.xml

---

songs/pl/kabaret/Wiosenna_piesn_radosci.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-17-6195-pl_kabaret_Wiosenna_piesn_radosci.xml&file=songs%2Fpl%2Fkabaret%2FWiosenna_piesn_radosci.xml&user=dch-pub)
Piosenka Wiosenna pieśń radości: Initial
Piosenka Wiosenna pieśń radości: ...alternatywny tytul i chwyty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-17-6195-pl_kabaret_Wiosenna_piesn_radosci.xml&file=songs%2Fpl%2Fkabaret%2FWiosenna_piesn_radosci.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/Wiosenna_piesn_radosci.xml

---

songs/pl/folk/kwiat_jabloni/buka.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-22-pl_folk_kwiat_jabloni_buka.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbuka.xml&user=dch-pub)
Piosenka Buka: ...nowe
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-16-22-pl_folk_kwiat_jabloni_buka.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbuka.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/buka.xml

---

songs/pl/folk/kwiat_jabloni/dzien_dobry.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-9582-pl_folk_kwiat_jabloni_dzien_dobry.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdzien_dobry.xml&user=dch-pub)
Piosenka Dzień Dobry: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-9582-pl_folk_kwiat_jabloni_dzien_dobry.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdzien_dobry.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/dzien_dobry.xml

---

editor-github/common.js
editor-github/deploy.sh
editor-github/index.js
editor-github/listChanges.js
editor/index.html
editor/songbook.js
src/latex/song2tex.py

- **The files loaded should support 'saving'.**
- **Fixes.**
- **Fixed auth redirect.**
redirect nie działał (i zawisał) przy URLach typu https vs. http.

Odświeżanie autoryzacji poprawione

---

songs/pl/folk/kwiat_jabloni/niemozliwe.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-5751-pl_folk_kwiat_jabloni_niemozliwe.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fniemozliwe.xml&user=dch-pub)
Piosenka Niemożliwe : ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-5751-pl_folk_kwiat_jabloni_niemozliwe.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fniemozliwe.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/niemozliwe.xml

---

songs/pl/folk/kwiat_jabloni/od_nowa.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-5201-pl_folk_kwiat_jabloni_od_nowa.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fod_nowa.xml&user=dch-pub)
Piosenka Od nowa: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-5201-pl_folk_kwiat_jabloni_od_nowa.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fod_nowa.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/od_nowa.xml

---

songbooks/smoke.songbook.yaml
src/epub/templates/song.css
src/html/create_songs_html.py

- chords on the left
- numbering of verses.

Align formatting of the html/epub songs with pdf (tex) songs.

---

songs/pl/poezja/Bar_w_Beskidzie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-22-4889-pl_poezja_Bar_w_Beskidzie.xml&file=songs%2Fpl%2Fpoezja%2FBar_w_Beskidzie.xml&user=ptabor)
Piosenka Bar w Beskidzie: Initial
Piosenka Bar w Beskidzie: To pierwsze to zwrotka
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-22-4889-pl_poezja_Bar_w_Beskidzie.xml&file=songs%2Fpl%2Fpoezja%2FBar_w_Beskidzie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/Bar_w_Beskidzie.xml

---

songs/pl/poezja/kasper.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-9662-pl_poezja_kasper.xml&file=songs%2Fpl%2Fpoezja%2Fkasper.xml&user=ptabor)
Piosenka Kasper: Jeszcze raz wersja Dorotki
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-21-9662-pl_poezja_kasper.xml&file=songs%2Fpl%2Fpoezja%2Fkasper.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/kasper.xml

---

songs/pl/folk/kwiat_jabloni/wodymidaj.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-23-6038-pl_folk_kwiat_jabloni_wodymidaj.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwodymidaj.xml&user=dch-pub)
Piosenka Wodymidaj: ...nowe
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-23-6038-pl_folk_kwiat_jabloni_wodymidaj.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwodymidaj.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/wodymidaj.xml

---

songs/pl/folk/kwiat_jabloni/wzieli_zamkneli_mi_klub.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-3703-pl_folk_kwiat_jabloni_wzieli_zamkneli_mi_klub.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwzieli_zamkneli_mi_klub.xml&user=dch-pub)
Piosenka Wzięli zamknęli mi klub: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-3703-pl_folk_kwiat_jabloni_wzieli_zamkneli_mi_klub.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwzieli_zamkneli_mi_klub.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/wzieli_zamkneli_mi_klub.xml

---

songs/pl/folk/kwiat_jabloni/Idzie_zima.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-2827-pl_folk_kwiat_jabloni_Idzie_zima.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2FIdzie_zima.xml&user=dch-pub)
Piosenka Idzie zima: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-2827-pl_folk_kwiat_jabloni_Idzie_zima.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2FIdzie_zima.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/Idzie_zima.xml

---

songs/pl/folk/kwiat_jabloni/byle_jak.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-8284-pl_folk_kwiat_jabloni_byle_jak.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbyle_jak.xml&user=dch-pub)
Piosenka Byle jak: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-8284-pl_folk_kwiat_jabloni_byle_jak.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fbyle_jak.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/byle_jak.xml

---

songs/pl/folk/kwiat_jabloni/dom.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-1746-pl_folk_kwiat_jabloni_dom.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdom.xml&user=dch-pub)
Piosenka Dom: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-1746-pl_folk_kwiat_jabloni_dom.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdom.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/dom.xml

---

songs/pl/folk/kwiat_jabloni/za_siodma_gora.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-4514-pl_folk_kwiat_jabloni_za_siodma_gora.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fza_siodma_gora.xml&user=dch-pub)
Piosenka Za siódmą chmurą: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-4514-pl_folk_kwiat_jabloni_za_siodma_gora.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fza_siodma_gora.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/za_siodma_gora.xml

---

songs/pl/pop/kazik/twoj_bol_jest_lepszy.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-3119-pl_pop_kazik_twoj_bol_jest_lepszy.xml&file=songs%2Fpl%2Fpop%2Fkazik%2Ftwoj_bol_jest_lepszy.xml&user=dch-pub)
Piosenka Twój ból jest lepszy niż mój: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-3119-pl_pop_kazik_twoj_bol_jest_lepszy.xml&file=songs%2Fpl%2Fpop%2Fkazik%2Ftwoj_bol_jest_lepszy.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/kazik/twoj_bol_jest_lepszy.xml

---

songs/pl/pop/Autobiografia.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-9641-pl_pop_Autobiografia.xml&file=songs%2Fpl%2Fpop%2FAutobiografia.xml&user=dch-pub)
Piosenka Autobiografia: Initial
Piosenka Autobiografia: ...dodane akordy
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-9641-pl_pop_Autobiografia.xml&file=songs%2Fpl%2Fpop%2FAutobiografia.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/Autobiografia.xml

---

songs/pl/pop/kazik/baranek.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-8371-pl_pop_kazik_baranek.xml&file=songs%2Fpl%2Fpop%2Fkazik%2Fbaranek.xml&user=dch-pub)
Piosenka Baranek: ...nowe
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-8371-pl_pop_kazik_baranek.xml&file=songs%2Fpl%2Fpop%2Fkazik%2Fbaranek.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/kazik/baranek.xml

---

songs/pl/pop/kazik/Celina.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-2311-pl_pop_kazik_Celina.xml&file=songs%2Fpl%2Fpop%2Fkazik%2FCelina.xml&user=dch-pub)
Piosenka Celina: ...nowe
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-26-2311-pl_pop_kazik_Celina.xml&file=songs%2Fpl%2Fpop%2Fkazik%2FCelina.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/kazik/Celina.xml

---

songs/pl/folk/kwiat_jabloni/zasnalem_na_trawniku.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-2650-pl_folk_kwiat_jabloni_zasnalem_na_trawniku.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fzasnalem_na_trawniku.xml&user=dch-pub)
Piosenka Zasnąłem na trawniku: ...nowa chyba lepiej nie umiem
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-25-2650-pl_folk_kwiat_jabloni_zasnalem_na_trawniku.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fzasnalem_na_trawniku.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/folk/kwiat_jabloni/zasnalem_na_trawniku.xml

---

songs/pl/poezja/obok_ciebie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-28-8455-pl_poezja_obok_ciebie.xml&file=songs%2Fpl%2Fpoezja%2Fobok_ciebie.xml&user=ptabor)
Piosenka Obok Ciebie: Initial
Piosenka Obok Ciebie: Gatunek normalization
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-28-8455-pl_poezja_obok_ciebie.xml&file=songs%2Fpl%2Fpoezja%2Fobok_ciebie.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/obok_ciebie.xml

---

songs/pl/harc/idalesni.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-01-3124-pl_harc_idalesni.xml&file=songs%2Fpl%2Fharc%2Fidalesni.xml&user=dch-pub)
Piosenka Idą leśni: ...nowa nowego typu
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-01-3124-pl_harc_idalesni.xml&file=songs%2Fpl%2Fharc%2Fidalesni.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/harc/idalesni.xml

---

songs/pl/harc/harcerska_dola.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-01-3013-pl_harc_harcerska_dola.xml&file=songs%2Fpl%2Fharc%2Fharcerska_dola.xml&user=dch-pub)
Piosenka Harcerska dola: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-01-3013-pl_harc_harcerska_dola.xml&file=songs%2Fpl%2Fharc%2Fharcerska_dola.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/harc/harcerska_dola.xml

---

songs/pl/kabaret/Sliczna_higieniczna.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-30-9596-pl_kabaret_Sliczna_higieniczna.xml&file=songs%2Fpl%2Fkabaret%2FSliczna_higieniczna.xml&user=ptabor)
Piosenka Śliczna higieniczna: Initial
Piosenka Śliczna higieniczna: Poprawienie twórców
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-09-30-9596-pl_kabaret_Sliczna_higieniczna.xml&file=songs%2Fpl%2Fkabaret%2FSliczna_higieniczna.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/Sliczna_higieniczna.xml

---

editor/sanitize.js
editor/songbody.js

- **Normalization**
- **Copy paste from varios sources (like plain-test editors, google docs, etc) should behave better.**

20241003 better copy paste

---

songs/pl/poezja/nadal_bede.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-03-1846-pl_poezja_nadal_bede.xml&file=songs%2Fpl%2Fpoezja%2Fnadal_bede.xml&user=dch-pub)
Piosenka Nadal będę: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-03-1846-pl_poezja_nadal_bede.xml&file=songs%2Fpl%2Fpoezja%2Fnadal_bede.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/nadal_bede.xml

---

songs/pl/poezja/przebudzenie.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-02-4924-pl_poezja_przebudzenie.xml&file=songs%2Fpl%2Fpoezja%2Fprzebudzenie.xml&user=dch-pub)
Piosenka Przebudzenie: ...nowe
Piosenka Przebudzenie: ...nowa
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-02-4924-pl_poezja_przebudzenie.xml&file=songs%2Fpl%2Fpoezja%2Fprzebudzenie.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/przebudzenie.xml

---

songs/pl/kabaret/baba_na_psy.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-09-35-pl_kabaret_baba_na_psy.xml&file=songs%2Fpl%2Fkabaret%2Fbaba_na_psy.xml&user=dch-pub)
Piosenka Baba na psy: ...z wywroty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-09-35-pl_kabaret_baba_na_psy.xml&file=songs%2Fpl%2Fkabaret%2Fbaba_na_psy.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/baba_na_psy.xml

---

songs/pl/poezja/absztyfikanci_grubej_berty.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-08-6616-pl_poezja_absztyfikanci_grubej_berty.xml&file=songs%2Fpl%2Fpoezja%2Fabsztyfikanci_grubej_berty.xml&user=dch-pub)
Piosenka Absztyfikanci Grubej Berty: ...import z wywroty+moje zmiany / poprawa akordow
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-08-6616-pl_poezja_absztyfikanci_grubej_berty.xml&file=songs%2Fpl%2Fpoezja%2Fabsztyfikanci_grubej_berty.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/absztyfikanci_grubej_berty.xml

---

songs/pl/poezja/wiewiorka.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-08-7153-pl_poezja_wiewiorka.xml&file=songs%2Fpl%2Fpoezja%2Fwiewiorka.xml&user=dch-pub)
Piosenka Wiewiórka: ...z wywroty, poprawione chwyty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-08-7153-pl_poezja_wiewiorka.xml&file=songs%2Fpl%2Fpoezja%2Fwiewiorka.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/wiewiorka.xml

---

songs/pl/kabaret/krolowa_nadbaltyckich_raf.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-11-8217-pl_kabaret_krolowa_nadbaltyckich_raf.xml&file=songs%2Fpl%2Fkabaret%2Fkrolowa_nadbaltyckich_raf.xml&user=dch-pub)
Piosenka Królowa Nadbałtyckich Raf: ...nowa z wywroty, nie sprawdzilam chwytów... mam nadzieje ze sa ok
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-11-8217-pl_kabaret_krolowa_nadbaltyckich_raf.xml&file=songs%2Fpl%2Fkabaret%2Fkrolowa_nadbaltyckich_raf.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/krolowa_nadbaltyckich_raf.xml

---

.gitignore
editor/conv/converter.js
editor/conv/converter.sh
editor/conv/lyric.test.js
editor/conv/package-lock.json
editor/conv/package.json
editor/conv/song.test.js
editor/package.json
requirements.txt
src/latex/song2tex.py

- **Experimenting with conversions.**
- **Copy paste from varios sources (like plain-test editors, google docs, etc) should behave better.**
- **Conversions**
- **Fix conversion and resilience to corrupted models.**

20240928 normalizations

---

editor/conv/conv.js
editor/conv/converter.js
editor/conv/lyric.test.js
editor/conv/package-lock.json
editor/conv/package.json
editor/conv/song.test.js
editor/songbook.js

- **Experimenting with conversions.**
- **Make all the code a proper ES6 node modules.**
- **Import file supports html originating from external songbooks.**

Import option - can support html from an external source

---

songs/pl/poezja/rudy_gosc.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-14-7550-pl_poezja_rudy_gosc.xml&file=songs%2Fpl%2Fpoezja%2Frudy_gosc.xml&user=dch-pub)
Piosenka Rudy gość: ...nie mam siły chwilowo dodawać chwytów nad... przepraszam
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-14-7550-pl_poezja_rudy_gosc.xml&file=songs%2Fpl%2Fpoezja%2Frudy_gosc.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/rudy_gosc.xml

---

songs/pl/kabaret/Diridindonda.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-16-9129-pl_kabaret_Diridindonda.xml&file=songs%2Fpl%2Fkabaret%2FDiridindonda.xml&user=dch-pub)
Piosenka Diridonda: ...import jednak z pliku + chwyty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-16-9129-pl_kabaret_Diridindonda.xml&file=songs%2Fpl%2Fkabaret%2FDiridindonda.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/Diridindonda.xml

---

songs/pl/kabaret/jagienka_i_orzechy.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-13-6836-pl_kabaret_jagienka_i_orzechy.xml&file=songs%2Fpl%2Fkabaret%2Fjagienka_i_orzechy.xml&user=ptabor)
Piosenka Jagienka i orzechy: JAgienka i Orzechy
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-13-6836-pl_kabaret_jagienka_i_orzechy.xml&file=songs%2Fpl%2Fkabaret%2Fjagienka_i_orzechy.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/jagienka_i_orzechy.xml

---

songs/pl/pop/orla_cien.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-560-pl_pop_orla_cien.xml&file=songs%2Fpl%2Fpop%2Forla_cien.xml&user=dch-pub)
Piosenka Orła cień: ...nowa z sieci
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-560-pl_pop_orla_cien.xml&file=songs%2Fpl%2Fpop%2Forla_cien.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/orla_cien.xml

---

songs/pl/kabaret/dam_ci_ptaszka.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-6935-pl_kabaret_dam_ci_ptaszka.xml&file=songs%2Fpl%2Fkabaret%2Fdam_ci_ptaszka.xml&user=dch-pub)
Piosenka Dam ci ptaszka: ...nowa z sieci bez akordow
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-6935-pl_kabaret_dam_ci_ptaszka.xml&file=songs%2Fpl%2Fkabaret%2Fdam_ci_ptaszka.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/dam_ci_ptaszka.xml

---

songs/pl/kabaret/pilem_w_spale_spalem.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-4440-pl_kabaret_pilem_w_spale_spalem.xml&file=songs%2Fpl%2Fkabaret%2Fpilem_w_spale_spalem.xml&user=dch-pub)
Piosenka Piłem w Spale, spałem w Pile: ...nowa z sieci
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-4440-pl_kabaret_pilem_w_spale_spalem.xml&file=songs%2Fpl%2Fkabaret%2Fpilem_w_spale_spalem.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/pilem_w_spale_spalem.xml

---

songs/pl/kabaret/nazywali_go_marynarz.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-4461-pl_kabaret_nazywali_go_marynarz.xml&file=songs%2Fpl%2Fkabaret%2Fnazywali_go_marynarz.xml&user=dch-pub)
Piosenka Nazywali go Marynarz  (szanta narciarska): ...nowa z sieci
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-23-4461-pl_kabaret_nazywali_go_marynarz.xml&file=songs%2Fpl%2Fkabaret%2Fnazywali_go_marynarz.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/nazywali_go_marynarz.xml

---

songs/pl/pop/zanim_zrozumiesz.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-9073-pl_pop_zanim_zrozumiesz.xml&file=songs%2Fpl%2Fpop%2Fzanim_zrozumiesz.xml&user=dch-pub)
Piosenka Zanim zrozumiesz: ...nowa z wywroty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-9073-pl_pop_zanim_zrozumiesz.xml&file=songs%2Fpl%2Fpop%2Fzanim_zrozumiesz.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/zanim_zrozumiesz.xml

---

songs/pl/pop/pocaluj_noc.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-9009-pl_pop_pocaluj_noc.xml&file=songs%2Fpl%2Fpop%2Fpocaluj_noc.xml&user=dch-pub)
Piosenka Pocałuj noc: ...nowa z wywroty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-9009-pl_pop_pocaluj_noc.xml&file=songs%2Fpl%2Fpop%2Fpocaluj_noc.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/pocaluj_noc.xml

---

songs/pl/pop/Ukraina.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-1362-pl_pop_Ukraina.xml&file=songs%2Fpl%2Fpop%2FUkraina.xml&user=dch-pub)
Piosenka Ukraina: Initial
Piosenka Ukraina: ...tytuł alternatywny, ale gatunek w sumie nie wiem
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-1362-pl_pop_Ukraina.xml&file=songs%2Fpl%2Fpop%2FUkraina.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/pop/Ukraina.xml

---

songs/pl/poezja/obozowe_tango.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-2852-pl_poezja_obozowe_tango.xml&file=songs%2Fpl%2Fpoezja%2Fobozowe_tango.xml&user=dch-pub)
Piosenka Obozowe Tango: ...z wywroty
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-2852-pl_poezja_obozowe_tango.xml&file=songs%2Fpl%2Fpoezja%2Fobozowe_tango.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/obozowe_tango.xml

---

songs/pl/kabaret/plastikowa_biedronko.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-1612-pl_kabaret_plastikowa_biedronko.xml&file=songs%2Fpl%2Fkabaret%2Fplastikowa_biedronko.xml&user=dch-pub)
Piosenka Pastikowa Biedronka: ...z wywroty, ale słowa nie do końca mi się podobają...
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-1612-pl_kabaret_plastikowa_biedronko.xml&file=songs%2Fpl%2Fkabaret%2Fplastikowa_biedronko.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/kabaret/plastikowa_biedronko.xml

---

songs/pl/koledy/gore_gwiazda.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-2737-pl_koledy_gore_gwiazda.xml&file=songs%2Fpl%2Fkoledy%2Fgore_gwiazda.xml&user=dch-pub)
Piosenka Gore gwiazda Jezusowi: ...wywrota, jest inna wersja chwytow
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-10-30-2737-pl_koledy_gore_gwiazda.xml&file=songs%2Fpl%2Fkoledy%2Fgore_gwiazda.xml&user=dch-pub) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/koledy/gore_gwiazda.xml

---

containers/Dockerfile
containers/build_push_images.sh
render_pdf.sh
songs/pl/poezja/Dym_z_jalowca.xml
src/formats/no-lg.xdy
src/formats/songbook_p.tex
src/latex/songbook21wdh.sty

- **No indexes in aliases.**
- **Dym z jałowca**
- **Improve index rendering in PDFs: Proper sorting by language.**

Improve index in PDF: Proper language based sorting.

---

songs/pl/poezja/Tango_na_glos_orkiestre_i_jeszcze_jeden_glos.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-11-02-8962-pl_poezja_Tango_na_glos_orkiestre_i_jeszcze_jeden_glos.xml&file=songs%2Fpl%2Fpoezja%2FTango_na_glos_orkiestre_i_jeszcze_jeden_glos.xml&user=ptabor)
Piosenka Tango na głos, orkiestrę i jeszcze jeden głos: Initial
Piosenka Tango na głos, orkiestrę i jeszcze jeden głos: Więcej akordów oznaczonych jako kluczowe (refren).
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-11-02-8962-pl_poezja_Tango_na_glos_orkiestre_i_jeszcze_jeden_glos.xml&file= …

Piosenka: songs/pl/poezja/Tango_na_glos_orkiestre_i_jeszcze_jeden_glos.xml

---

songs/pl/poezja/Kubus.xml

[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-11-09-7328-pl_poezja_Kubus.xml&file=songs%2Fpl%2Fpoezja%2FKubus.xml&user=ptabor)
Piosenka Kubuś: Initial
Piosenka Kubuś: Walczyk
Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org&branch=se-2024-11-09-7328-pl_poezja_Kubus.xml&file=songs%2Fpl%2Fpoezja%2FKubus.xml&user=ptabor) by nanieść dodatkowe poprawki.

Piosenka: songs/pl/poezja/Kubus.xml
